server.rb
The _comments.json file was getting cached and would not update the view when the json was changed.
=> read _comments.json after request received

README.md, server.php
Added a php server + updated the README file
=> PHP server

public/scripts/example.js
Removes unnecessary return to correspond to this [pull](https://github.com/facebook/react/pull/3016).
=> Remove unnecessary return

public/css/base.css
=> Remove duplicated semicolon in base.css

server.go
Allocate []bytes for reading data in and write out indented JSON.
This should close #30
=> Updates based on #30

server.go
Just a couple things from #30 that didn't make it into #34
- log to stdout when starting the server
- send updated data on POST
- set content type headers
cc @freeformz
=> Improve Go server

public/index.html
For when we launch and cdnjs is updated.
I tested with fb.me and RC2 so this should be fine.
=> Point at 0.13

README.md, app.json, package.json, server.go, server.js, server.php, server.py, server.rb
Add's a Heroku Button so people can experiment w/o having to install anything locally.
=> Heroku button

public/index.html, public/scripts/example.js
=> Use marked instead of Showdown and escape HTML

comments.json
The React tutorial makes use of the marked library, but this test data in the repo doesn't include any Markdown. Just makes for a more interesting tutorial IMO.
=> Added Markdown content to comments.json.

public/scripts/example.js
example.js was out of sync with the tutorial; handleCommentSubmit does not need a call back.
=> Updating example.js to match tutorial

server.go, server.rb
Let's have a lint for awesome react tutorial :)
Confirmed that the server ran well with go and ruby.
=> Lint for go and ruby

README.md, Server.hs, public/scripts/example.js, server.go, server.js, server.lua, server.php, server.py, server.rb
Like #48 but updated for all the servers that exist now and with a different endpoint.
=> Use an API endpoint

public/index.html
I'll merge this when we update ensure our docs completely reflect this same thing.
=> Use Babel to transform JSX

README.md
Adds "Changing the port" section to the README.
=> Add port-change info

public/scripts/example.js
Not sure why this wasn't incorporated into the tutorial, it is obviously essential for optimistic updates.
=> Fix failure to roll back optimistic update after error

public/scripts/example.js
Related to doc changes in React repo: https://github.com/facebook/react/pull/5445
=> Use controlled components for form inputs

public/index.html
Minor updates to the lastest versions of the CDN dependencies.
=> Update CDN links to latest versions

public/index.html, public/scripts/example.js
=> Use remarkable instead of marked

public/index.html
Updated react source to latest version. This fixes an issue with handling event handler returns and makes project code agree with the sample code on [https://facebook.github.io/react/docs/tutorial.html](url)
=> Update React Dependency to 15.1.0

public/index.html
cf https://github.com/facebook/react/pull/7394
=> Use npmcdn
